version: '3.2'
services:
  epp-mongo-shardsvr:
    container_name: epp-${img_name}-${svr_name}-${cont_postfix}${cont_num}
    image: epp-${img_name}:${img_ver}
    user: ${cont_user}
    command: ${cmd_val}
    privileged: true
    ports:
      - ${host_port}:${cont_port}
    volumes:
      - ${vol_from_db}:${vol_to_db}
      - ${vol_from_tmp}:${vol_to_tmp}
      - ${vol_from_etc}:${vol_to_etc}
      - ${vol_from_save}:${vol_to_save}
      - ${vol_from_os_tmp}:${vol_to_os_tmp}
      - ${vol_from_epp_etc}:${vol_to_epp_etc}
