apiVersion: v1
kind: Pod
metadata:
  name: es
  namespace: epp
  labels:
    name: pod-es
spec:
  containers:
    - name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
      ports:
        - containerPort: 9200
          name: external-rest-api
        - containerPort: 9300
          name: internal-tcp
      volumeMounts:
        - name: storage-db-es
          mountPath: /usr/share/elasticsearch
        - name: localitme
          mountPath: /etc/localtime:ro
  volumes:
    - name: storage-db-es
      hostPath:
        path: /opt/ahnlab/epp/elasticsearch-6.2.2
        type: Directory
    - name: localtime
      hostPath:
        path: /etc/localtime
        type: File
